apiVersion: v1
kind: Service
metadata:
  name: vb-django
spec:
  selector:
    app: vb-django
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vb-django-pvolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: C:\git\vb\vb_kube\vb_django
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: static-pv1
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vb-django-pvolume-claim1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vb-django
  name: vb-django
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app: vb-django
  template:
    metadata:
      labels:
        app: vb-django
    spec:
      hostname: vb-django
      containers:
      - name: vb-django
        image: quanted/vb_django:latest
        imagePullPolicy: Always
        env:
          - name: IN_DOCKER
            value: True
          - name: DJANGO_SETTINGS_MODULE
            value: vb_django.settings
          - name: DASK_SCHEDULER
            value: dask-scheduler:8786
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/app
          name: vb-django-volume
      restartPolicy: Always
      volumes:
      - name: vb-django-volume
        persistentVolumeClaim:
          claimName: vb-django-pvolume-claim1