apiVersion: v1
kind: Service
metadata:
  name: vb-django
spec:
  type: NodePort
  selector:
    app: vb-django
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000

#---
#
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: vb-django-pvolume
#spec:
#  accessModes:
#  - ReadWriteMany
#  capacity:
#    storage: 1Gi
#  hostPath:
#    path: "/Users/dsmith/Documents/git/vb_kube/vb_django"
#  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: standard
#  volumeMode: Filesystem
#
#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: vb-django-pvolume-claim
#spec:
#  accessModes:
#    - ReadWriteMany
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 8Gi
#  storageClassName: standard
#  selector:
#    matchLabels:
#      release: "stable"
#      name: vb-django-pvolume

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vb-django
  name: vb-django
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app: vb-django
  template:
    metadata:
      labels:
        app: vb-django
    spec:
      hostname: vb-django
      containers:
      - name: vb-django
        image: quanted/vb_django:latest
        imagePullPolicy: Always
        env:
          - name: IN_DOCKER
            value: "True"
          - name: DJANGO_SETTINGS_MODULE
            value: "vb_django.settings"
          - name: DASK_SCHEDULER
            value: "dask-scheduler:8786"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/app/vb_django/
          name: vb-django-volume
      restartPolicy: Always
      volumes:
      - name: vb-django-volume
        hostPath:
          path: /Users/dsmith/Documents/git/vb_kube/vb_django
          type: Directory
